services:
  core:
    build: 
      context: ./
      dockerfile: ./doorbird_core/dockerfile
    networks:
      - doorbird-net
    ports:
      - '6524:6524/udp'
    volumes:
      - doorbird-conf:/etc/core/conf
      - doorbird-log:/etc/core/log
    restart: always
  chime:
    build: 
      context: ./
      dockerfile: ./doorbird_chime/dockerfile
    depends_on:
      - core
    networks:
      - doorbird-net
    volumes:
      - doorbird-sounds:/etc/chime/sounds
    devices:
      - '/dev/snd:/dev/snd'
    restart: always
  control-back:
    build: 
      context: ./
      dockerfile: ./doorbird_control_back/dockerfile
    depends_on:
      - core
    networks:
      - doorbird-net
    volumes:
      - doorbird-conf:/etc/serv/conf
      - doorbird-log:/etc/serv/log
      - doorbird-sounds:/etc/serv/sounds
      - doorbird-images:/etc/serv/images
    restart: always
  control-front:
    depends_on:
      - core
      - control-back
    build: 
      context: ./
      dockerfile: ./doorbird_control_front/dockerfile
    ports:
      - '${front_http_port}:80'
      - '${front_https_port}:443'
    networks:
      - doorbird-net
    restart: always
  watcher:
    depends_on:
      - core
    build: 
      context: ./
      dockerfile: ./doorbird_watcher/dockerfile
    networks:
      - doorbird-net
    volumes:
      - doorbird-conf:/etc/serv/conf
      - doorbird-images:/etc/serv/images
    restart: always

volumes:
  doorbird-conf: {}
  doorbird-log: {}
  doorbird-sounds: {}
  doorbird-images: {}

networks:
  doorbird-net: {}
