services:
  core:
    build: ./doorbird_core
    networks:
      - doorbird-net
    ports:
      - '6524:6524/udp'
    volumes:
      - doorbird-conf:/etc/core/conf
      - doorbird-log:/etc/core/log
    restart: always
  chime:
    build: ./doorbird_chime
    depends_on:
      - core
    networks:
      - doorbird-net
    volumes:
      - doorbird-sounds:/etc/chime/sounds
    devices:
      - '/dev/snd:/dev/snd'
    restart: always
  control-back:
    build: ./doorbird_control_back
    depends_on:
      - core
    ports:
      - '5004:80'
    networks:
      - doorbird-net
    volumes:
      - doorbird-conf:/etc/serv/conf
      - doorbird-log:/etc/serv/log
      - doorbird-sounds:/etc/serv/sounds
    restart: always
  control-front:
    depends_on:
      - core
      - control-back
    build: ./doorbird_control_front
    ports:
      - '5005:80'
      - '5006:443'
    networks:
      - doorbird-net
    restart: always

volumes:
  doorbird-conf: {}
  doorbird-log: {}
  doorbird-sounds: {}

networks:
  doorbird-net: {}
