services:
  chime:
    build: ./doorbird_chime
    ports:
      - '6524:6524/udp'
    networks:
      - doorbird-net
    volumes:
      - doorbird-conf:/etc/chime/conf
      - doorbird-log:/etc/chime/log
      - doorbird-sounds:/etc/chime/sounds
    devices:
      - '/dev/snd:/dev/snd'
    restart: always
  back:
    build: ./doorbird_control_back
    ports:
      - '5004:80'
    networks:
      - doorbird-net
    volumes:
      - doorbird-conf:/etc/serv/conf
      - doorbird-sounds:/etc/serv/sounds
    restart: always
  front:
    build: ./doorbird_control_front
    ports:
      - '80:80'
      - '443:443'
    networks:
      - doorbird-net
    restart: always

volumes:
  doorbird-conf: {}
  doorbird-log: {}
  doorbird-sounds: {}

networks:
  doorbird-net: {}
