FROM alpine:latest
COPY requirements.txt requirements.txt
RUN apk add --no-cache python3 py-pip && \
    pip install -r requirements.txt
COPY . /etc/serv
WORKDIR /etc/serv
CMD ["python3", "-u", "app/serv.py"]