FROM alpine:latest
COPY ./doorbird_control_back/requirements.txt requirements.txt
RUN apk add --virtual .build-deps gcc python3-dev musl-dev && \
    apk add --no-cache python3 py-pip jpeg-dev zlib-dev libjpeg ffmpeg && \
    pip install -r requirements.txt --break-system-packages && \
    apk del .build-deps
COPY ./doorbird_control_back /etc/serv
COPY ./doorbird_common /etc/serv/app/common
WORKDIR /etc/serv
CMD ["python3", "-u", "app/serv.py"]
