FROM alpine:latest
COPY ./doorbird_control_back/requirements.txt requirements.txt
RUN apk add --no-cache python3 py-pip && \
    pip install -r requirements.txt
COPY ./doorbird_control_back /etc/serv
COPY ./doorbird_common /etc/serv/app/common
WORKDIR /etc/serv
CMD ["python3", "-u", "app/serv.py"]