FROM alpine:latest
COPY requirements.txt requirements.txt
RUN apk add --no-cache python3 py-pip alsa-utils && \
    pip install -r requirements.txt
COPY . /etc/chime
WORKDIR /etc/chime
CMD ["python3", "-u", "app/serv.py"]
