name: BuildPush

on:
    push:
        branches:
            - 'main'
            - 'dev'
            - 'feat**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v1
              with:
                registry: ws11containerreg.azurecr.io
                username: ${{ vars.REGISTRY_USER }}
                password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: Build & Push
              run:  docker buildx bake --push --set *.platform=linux/arm64,linux/arm/v6